name: fwts
version: V21.12.00
summary: The Firmware Test Suite (FWTS)
description: This is a firmware test suite that performs sanity checks on system firmware. It is intended to identify BIOS and ACPI errors and if appropriate it will try to explain the errors and give advice to help workaround or fix firmware bugs.  It is primarily intended to be a Linux-centric firmware troubleshooting tool.
confinement: strict
type: app
grade: stable
assumes: [snapd2.45]
base: core20

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    fwts:
        plugin: autotools
        source: git://kernel.ubuntu.com/hwe/fwts
        stage-packages:
            - libfdt1
            - libbsd0
            - libpci3
        build-packages:
            - gcc
            - make
            - autoconf
            - automake
            - libtool
            - flex
            - bison
            - dh-autoreconf
            - libglib2.0-dev
            - libfdt-dev
            - libbsd-dev
apps:
    fwts:
        plugs: [home, hardware-observe, io-ports-control, kernel-module-control, log-observe, system-observe ]
        command: usr/local/bin/fwts
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib/fwts
