name: fwts
version: V18.06.01
summary: The Firmware Test Suite (FWTS)
description: This is a firmware test suite that performs sanity checks on system firmware. It is intended to identify BIOS and ACPI errors and if appropriate it will try to explain the errors and give advice to help workaround or fix firmware bugs.  It is primarily intended to be a Linux-centric firmware troubleshooting tool.
confinement: devmode

parts:
    fwts:
        plugin: autotools
        source: git://kernel.ubuntu.com/hwe/fwts
        stage-packages:
            - libfdt1
        build-packages:
            - gcc
            - make
            - autoconf
            - automake
            - libtool
            - libjson-c-dev
            - flex
            - bison
            - dh-autoreconf
            - libglib2.0-dev
            - libfdt-dev
apps:
    fwts:
        command: bin/fwts
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/fwts
